num_channels: 3
num_kp: 13
MotionModule:
  KeypointDetector:
    layer_xp: 16
    num_layers: 5
    max_channel: 256
    temperature: 0.1
    jacobian: True
  DenseMotion:
    layer_xp: 16
    num_layers: 5
    max_channel: 256
    occlusion: True
GenerationModule:
  layer_xp: 32
  num_layers: 2
  num_reslayers: 6
  max_channel: 256
loss:
  scales: [1.]
  requires_grad_vgg: False
  equivariance_constraint_value: True
  equivariance_constraint_jacobian: True
train:
  num_epochs: 15
  lr: 1e-4
  milestones_lr: [5, 10]
  gamma: 0.1
data_sampler:
  num_sample: 100
  resolution: '360p'
  size_out: [64, 64]
data_loader:
  batch_size: 16
  shuffle: True