num_channels: 3
num_kp: 13
MotionModule:
  KeypointDetector:
    layer_xp: 64
    num_layers: 3
    max_channel: 512
    temperature: 0.1
    jacobian: True
  DenseMotion:
    layer_xp: 64
    num_layers: 5
    max_channel: 512
    occlusion: True
  scale_opticalflow: 0.5
GenerationModule:
  layer_xp: 64
  num_layers: 1
  num_reslayers: 6
  max_channel: 256
  scalestep: 2
transform:
  scale_std: 0.5
  shift_std: 0.3
loss:
  scales: [1, 0.75, 0.5, 0.25]
  equivariance_constraint_value: True
  equivariance_constraint_jacobian: True
  weight_loss: [1., 0.87, 0.87]
train:
  num_epochs: 20
  lr: 1.0e-4
  milestones_lr: [6, 12, 18]
  gamma: 0.1
data_loader:
  batch_size: 56
  shuffle: True
