num_channels: 3
num_kp: 15
MotionModule:
  KeypointDetector:
    layer_xp: 64
    num_layers: 3
    max_channel: 256
    temperature: 0.1
    jacobian: True
  DenseMotion:
    layer_xp: 16
    num_layers: 5
    max_channel: 256
    occlusion: True
GenerationModule:
  layer_xp: 64
  num_layers: 1
  num_reslayers: 8
  max_channel: 256
transform:
  scale_std: 0.5
  shift_std: 0.3
loss:
  scales: [1, 0.75, 0.5]
  equivariance_constraint_value: True
  equivariance_constraint_jacobian: True
train:
  num_epochs: 15
  lr: 1.0e-4
  milestones_lr: [4, 8, 12]
  gamma: 0.1
data_sampler:
  num_sample: 100
  resolution: '360p'
  size_out: [64, 64]
data_loader:
  batch_size: 16
  shuffle: True